apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: python-template

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore

  target:
    name: python-template-secret
    creationPolicy: Owner

  data:
    - secretKey: APP_ENV
      remoteRef:
        key: aws-k8s-project/dev/python-template
        property: APP_ENV

    - secretKey: API_MESSAGE
      remoteRef:
        key: aws-k8s-project/dev/python-template
        property: API_MESSAGE