apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: aws-secrets-manager

spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-east-1

      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets