architecture: standalone

auth:
  enabled: true
  rootUser: root
  existingSecret: mongodb-secret

persistence:
  enabled: true
  storageClass: gp3
  size: 5Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi

  limits:
    cpu: 1000m
    memory: 2Gi