apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb
  namespace: platform
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: mongodb-secret
    creationPolicy: Owner

  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: aws-k8s-project/dev/mongodb
        property: mongodb-root-password