global:
  domain: ""

configs:
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: HTTP
    paths:
      - /