apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  project: default

  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.8.0
      helm:
        valueFiles:
          - $values/platform/helm-values/external-secrets/values.yaml

    - repoURL: https://github.com/tonyrosset/aws-k8.git
      targetRevision: dev
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true