apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret-resources
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  source:
    repoURL: https://github.com/tonyrosset/aws-k8.git
    targetRevision: dev
    path: platform/external-secrets
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true