apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orion-ld
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  sources:
    - repoURL: https://fiware.github.io/helm-charts
      chart: orion
      targetRevision: 1.6.11
      helm:
        valueFiles:
          - $values/platform/helm-values/orion-ld/values.yaml

    - repoURL: https://github.com/tonyrosset/aws-k8.git
      targetRevision: dev
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: fiware-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true