name: Terraform Validate

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'infra/**'
  pull_request:
    paths:
      - 'infra/**'

jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    strategy:
        matrix:
            working-directory:
                - 'infra/environments/dev/core'
                - 'infra/environments/dev/platform'

    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate